### ISSUE TITLE
404 Page Errors On Hydration

### ISSUE THREAD

**Issue by Undistraction** [AndreasFaust/gatsby-plugin-htaccess#2]
Using the default 404 config:
```
ErrorDocument 404 /404/index.html
```

Gatsby does serve the 404 page, but throws an error on hydration of the page:

> A page wasn't found for "/missing"

The error originates in Gatsby's `EnsureResources` which is checking that Gatsby has the appropriate resources for a given page. However it is looking for the resources of the missing page which it obviously doesn't have.

**Comment by AndreasFaust** [comment]
Thank you for the hint. 
The error appears only in development, am I right? 
How can a .htaccess-file interfere there?

**Comment by AndreasFaust** [comment]
Thank you for the hint. 
The error appears only in development, am I right? 
How can a .htaccess-file interfere there?

**Comment by Undistraction** [comment]
No. This is a production only issue. There are no issues in development, only when deployed to Apache and using the above `.htaccess` config to handle errors. I'll try and put a repro together.

Can you confirm that this config serves a 404 page without error? Bear in mind it will look like the page has loaded successfully unless you have the console open or try and navigate using a Gatsby Link (which will result in the URL in the address bar changing, but the page content not changing).

**Comment by Undistraction** [comment]
I have a repro. 

Repository [here](https://github.com/Undistraction/gatsby-404-error). Note I have only the single `ErrorDocument 404 /404/index.html` line in the `.htaccess` file.

Deployed here undistraction.club

If you navigate to http://undistraction.club/blah you will see the error in the console.

**Comment by AndreasFaust** [comment]
I also get a hint `A page wasn't found for "/missing"` in the console, but everything works as expected on my Apache test-server.

**Comment by AndreasFaust** [comment]
Could you solve the problem? 
If not, please give me some information about your server environment and Gatsby version, that I can reproduce the error.

**Comment by Undistraction** [comment]
@AndreasFaust Thanks for sticking with it. I've just solved it -a very obscure issue related to using `gatsby-plugin-remove-trailing-slashes`. Had nothing at all to do with this library. Sorry for the noise and thanks for trying to help.

**Comment by AndreasFaust** [comment]
No problem!

**Comment by enyo** [comment]
@Undistraction i'm running into the same issue. Do you remember how you solved it?
