### ISSUE TITLE
HTTP:X-Forwarded-Proto for HTTPS Redirection

### ISSUE THREAD

**Issue by louisiscoding** [AndreasFaust/gatsby-plugin-htaccess#3]
When using the default HTTPS redirection of this plugin, i'm facing a **ERR_TOO_MANY_REDIRECTS** error. This issue is referenced [here](https://aws.amazon.com/premiumsupport/knowledge-center/redirect-http-https-elb/?nc1=h_ls).
Due to the apache services i'm using, i would need to force https with theses rules :

```
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
```

I don't succeed to write this custom rule. Can you help me ?

**Comment by AndreasFaust** [comment]
Have you tries this? 

```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-htaccess',
      options: {
        https: false,
        custom: `
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
        `,
      },
    },
  ],
}
```

First disable the default https-handling (just to be sure, that there's no interference). 
Then write the custom-rule into the "custom"-string, which gets appended to the `.htaccess`-file.

**Comment by xbojch** [comment]
Could we add an extra flag like `forward: true` that in combination with `https: true` would generate something like
```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

**Comment by louisiscoding** [comment]
Awesome ! Thanks @xbojch
