### ISSUE TITLE
Expires headers for images

### ISSUE THREAD

**Issue by Undistraction** [AndreasFaust/gatsby-plugin-htaccess#4]
Would it make sense to add expires headers for images?

Currently cache headers are only added for html, service-worker and css/js:

```
<IfModule mod_headers.c>
    <FilesMatch "\.html$">
        Header set Cache-Control "public, max-age=0, must-revalidate"
    </FilesMatch>
    <FilesMatch "\.(js|css)$">
        Header set Cache-Control "public, max-age=31536000, immutable"
    </FilesMatch>
    <Files sw.js>
        Header set Cache-Control "public, max-age=0, must-revalidate"
    </Files>
</IfModule>
```

**Comment by AndreasFaust** [comment]
Images are stored in the folder `/public/static`. 
The module creates a second `.htaccess`-file inside there, which sets those headers.
https://github.com/AndreasFaust/gatsby-plugin-htaccess/blob/master/defaults/static-htaccess

Admittedly I didn't and still don’t know, how to integrate these directives into the main `.htaccess`. If there’s a way (it certainly is), it would be better to unify those files.
