### ISSUE TITLE
Prevent Caching of JSON in page-data dir

### ISSUE THREAD

**Issue by Undistraction** [AndreasFaust/gatsby-plugin-htaccess#6]
JSON files should be set not to cache (Chrome for example appears to cache them by default).

See: https://www.gatsbyjs.org/docs/caching/

> Similar to HTML files, the JSON files in the page-data directory should never be cached by the browser. In fact, it’s possible for these files to be updated even without doing a redeploy of your site. Because of this, browsers should be instructed to check on every request if the data in your application has changed.
> 
> The cache-control header should be cache-control: public, max-age=0, must-revalidate1

Currently JSON files are not included in the config:
```
<FilesMatch "\.html$">
  Header set Cache-Control "public, max-age=0, must-revalidate"
</FilesMatch>
<FilesMatch "\.(js|css)$">
  Header set Cache-Control "public, max-age=31536000, immutable"
</FilesMatch>
<Files sw.js>
  Header set Cache-Control "public, max-age=0, must-revalidate"
</Files>
```

**Comment by AndreasFaust** [comment]
Thank you for the hint! 
I fixed and released it (Version 1.2.2).
