### ISSUE TITLE
Customize the ErrorDocument

### ISSUE THREAD

**Issue by mschel** [AndreasFaust/gatsby-plugin-htaccess#8]
First - great plugin!

Is there a way to customize the `ErrorDocument` path?

Thanks

**Comment by AndreasFaust** [comment]
You can specify this by using the `custom`-option:
```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-htaccess',
      options: {
        custom: `
            ErrorDocument 404 /path/to/404.html
        `,
      },
    },
  ],
}
```

**Comment by mschel** [comment]
Already tried - this will add another `ErrorDocument` Definition at the End of the `.htaccess` File. Or is the last entry overriding the previous one by `.htaccess` Definition?

**Comment by AndreasFaust** [comment]
I've just added the option `ErrorDocument`. Update to version 1.3.1 and take a look at the `readme.md`.
If everything works and you want to do me a favour: `Star this library!`

**Comment by mschel** [comment]
works like a charm! Thanks
